

# hardcode list of merchants
FrequentMerchants = [
  {"name": "PoppersPad Chicken Bites", "id": 185},
  {"name": "Daily Joe", "id": 435},
  {"name": "Titooo's Restobar", "id": 480},
  {"name": "Riona's Kitchen", "id": 465},
  {"name": "Padayon Cafe", "id": 414},
  {"name": "El Classico Grilled", "id": 479}
]

AllMerchants = [
  {"name": "Airbrew Cafe", "id": 483},                                                                                                                    
  {"name": "AJL Chicken Bacolod", "id": 36},                                                                                                                        
  {"name": "AMANG's Grill and Resto Bar", "id": 200},                                                                                                               
  {"name": "Angel's Burger", "id": 447},                                                                                                                            
  {"name": "BABU", "id": 451},                                                                                                                                      
  {"name": "Baliwag Lechon Manok", "id": 34},                                                                                                                       
  {"name": "Basteakoy", "id": 384},                                                                                                                                 
  {"name": "Bhait Al Beryani Restaurant", "id": 353},                                                                                                               
  {"name": "BIGGS", "id": 305},                                                                                                                                     
  {"name": "BOB's Grill Point - NAGA", "id": 427},
  {"name": "Bubble Island Tea Shop ", "id": 275},
  {"name": "Bubble Town Tea House", "id": 53},
  {"name": "Caldi's Kitchen", "id": 171},
  {"name": "Champy's FuntaSticks", "id": 230},
  {"name": "Chef Buster Cuisine", "id": 276},
  {"name": "Chi Dietary", "id": 466},
  {"name": "Chowking Magsaysay", "id": 460},
  {"name": "Conde's Kitchen", "id": 234},
  {"name": "Crispy King", "id": 406},
  {"name": "Crown Park Restaurant", "id": 11},
  {"name": "Cuppa Coffee and Tea", "id": 274},
  {"name": "Dad's All Day Kitchen", "id": 38},
  {"name": "Daily Joe", "id": 435},
  {"name": "DCA Signature - Naga", "id": 438},
  {"name": "Doña Osang Catering Services", "id": 402},
  {"name": "Dos Kumpares", "id": 285},
  {"name": "Dunkin Donuts", "id": 450},
  {"name": "El Classico Grilled", "id": 479},
  {"name": "Fries To Go", "id": 178},
  {"name": "Graceland", "id": 25},
  {"name": "Green Earth Cafe", "id": 109},
  {"name": "Green Ralph", "id": 83},
  {"name": "Greenwich", "id": 448},
  {"name": "Grissini Ristorante", "id": 5},
  {"name": "gTEA", "id": 88},
  {"name": "Hapidee Daet", "id": 452},
  {"name": "Happy Kopi Naga City", "id": 426},
  {"name": "Hong Kong Style Fried Noodles", "id": 316},
  {"name": "Hoyeh", "id": 24},
  {"name": "Ice Blinker Halo-Halo & Fastfood", "id": 246},
  {"name": "Jade Plaza", "id": 13},
  {"name": "Japan Japan by Mitsuo San", "id": 19},
  {"name": "JCAE Chill & Dine", "id": 418},
  {"name": "Jireh's Authentic Takoyaki", "id": 105},
  {"name": "Jollibee Magsaysay", "id": 111},
  {"name": "KapeChie", "id": 444},
  {"name": "Kenny Rogers Roasters - SM City Naga", "id": 239},
  {"name": "KFC", "id": 449},
  {"name": "Kuya Chabz Lutong Bahay", "id": 277},
  {"name": "Kuya J Restaurant", "id": 115},
  {"name": "KwikSnaks Naga", "id": 416},
  {"name": "La Herencia Comida", "id": 299},
  {"name": "Layagan Bakery Toasted Siopao", "id": 280},
  {"name": "Lite Cafe", "id": 244},
  {"name": "Machichu Chicken", "id": 419},
  {"name": "Mang Inasal", "id": 103},
  {"name": "Mang Kok's Kinalas", "id": 123},
  {"name": "Manna Korea", "id": 32},
  {"name": "Marlicious by M&R", "id": 464},
  {"name": "Mashi Corndog", "id": 224},
  {"name": "McDonald's", "id": 428},
  {"name": "Mister Donut - Grand Master Mall", "id": 284},
  {"name": "Mister Donut - SM City Naga", "id": 26},
  {"name": "MLC & Co.", "id": 423},
  {"name": "Oyshini Takoyaki - St. Joseph School", "id": 271},
  {"name": "Oyster Restaurant", "id": 67},
  {"name": "Padayon Cafe", "id": 414},
  {"name": "Pansit Malabon", "id": 35},
  {"name": "Paotsin", "id": 439},
  {"name": "Pay Kiks Rapsa", "id": 99},
  {"name": "Peri Happy", "id": 9},
  {"name": "Perinoy Herbs and Spices", "id": 173},
  {"name": "Philia Coffee", "id": 257},
  {"name": "Pirate Shack", "id": 130},
  {"name": "Pizza Haus", "id": 110},
  {"name": "Pizza Pedrico's", "id": 120},
  {"name": "PoppersPad Chicken Bites", "id": 185},
  {"name": "Potato Corner - Ateneo", "id": 240},
  {"name": "Potato Corner - Grand Master Mall", "id": 65},
  {"name": "Poyang Special Biryani", "id": 481},
  {"name": "Puwestuhan Grill", "id": 252},
  {"name": "Razon's by Glenn - M Plaza", "id": 407},
  {"name": "Red Platter", "id": 4},
  {"name": "Riona's Kitchen", "id": 465},
  {"name": "Robinsons Supermarket Sisig", "id": 315},
  {"name": "Royaltea Brew Cafe", "id": 180},
  {"name": "Seeramitea", "id": 139},
  {"name": "Seeramity PH", "id": 89},
  {"name": "Selecta Ice Cream Store", "id": 17},
  {"name": "Sendang Ramen Food House", "id": 212},
  {"name": "Sgimirita Pizza", "id": 222},
  {"name": "Sgt. Sisig", "id": 114},
  {"name": "Shakey's Robinsons Place Naga", "id": 223},
  {"name": "Silog Spot", "id": 420},
  {"name": "Siomai King by KwikSnaks", "id": 424},
  {"name": "Soi Satay", "id": 136},
  {"name": "Soledad Restaurant", "id": 482},
  {"name": "Solido", "id": 241},
  {"name": "Starbucks Coffee", "id": 311},
  {"name": "Street Cafe", "id": 453},
  {"name": "Summer's Deli", "id": 206},
  {"name": "Sweet Tooth - Naga", "id": 245},
  {"name": "Take Me Out MPLaza", "id": 301},
  {"name": "Tanchahan Foods", "id": 462},
  {"name": "TapSig2Go", "id": 325},
  {"name": "Tea Bats", "id": 209},
  {"name": "Tea Tabz", "id": 179},
  {"name": "Tea Takei", "id": 192},
  {"name": "Teacups", "id": 117},
  {"name": "TeaTime Milktea House", "id": 21},
  {"name": "The New Dexter's Pizza", "id": 484},
  {"name": "thedays.co", "id": 238},
  {"name": "Titooo's Restobar", "id": 480},
  {"name": "Toob-Oh Treats", "id": 226},
  {"name": "Toshi O Japanese Restaurant", "id": 425},
  {"name": "Travel Cafe PH", "id": 168},
  {"name": "Triboo Grill", "id": 145},
  {"name": "Tugawe Cove Cafe", "id": 127},
  {"name": "Turks", "id": 445},
  {"name": "Uncle John's", "id": 310},
  {"name": "Wakins", "id": 461},
  {"name": "Western Plate", "id": 68},
  {"name": "Whip & Brew", "id": 169},
  {"name": "Whip It Good", "id": 189},
  {"name": "Wild Wings", "id": 91},
  {"name": "Yahm's Foodhub Naga", "id": 286},
  {"name": "Yoka Bubble", "id": 369},
  {"name": "Zabaldica's Litson Manok", "id": 242},
  {"name": "Zmokey's BBQ", "id": 404},
  {"name": "Zushi Me Naga", "id": 264}
]